name: delete release
on:
  workflow_dispatch:
    inputs:
      delete_target_release_tag:
        description: '削除したいリリースのタグを指定してください。'
        required: true
        type: string

env:
  TZ: 'Asia/Tokyo'
  REPOSITORY_OWNER: ganzinn
  REPOSITORY_NAME: sample

jobs:
  delete_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.delete_target_release_tag }}
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: output is_prerelease
        id: is_prerelease
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          is_prerelease=$(gh release view --json isPrerelease -q .isPrerelease ${{ github.event.inputs.delete_target_release_tag }})
          echo "is_prerelease=$is_prerelease" >> $GITHUB_OUTPUT

      - name: confirmation
        id: confirmation
        shell: bash
        run: |
          echo ${{ steps.is_prerelease.outputs.is_prerelease }}

      # - name: delete release
      #   id: delete_release
      #   shell: bash
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   # このステップは、delete_target_release_tagのreleaseが「Pre-release」の場合のみ実行
      #   if: ${{ needs.setup_environment.outputs.is_prerelease }} == true
      #   run: gh release delete ${{ github.event.inputs.delete_target_release_tag }}
